# Generated by Django 4.2.5 on 2024-03-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollments',
            options={'verbose_name_plural': 'Enrollments'},
        ),
    ]
