# Generated by Django 4.2.11 on 2024-04-30 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_remove_student_enrolled_courses'),
        ('Course', '0012_course_average_rank_studentcourserank'),
        ('Enrollments', '0002_alter_enrollments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollments',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.course'),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student'),
        ),
        migrations.AddConstraint(
            model_name='enrollments',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_enrollment'),
        ),
    ]
