# Generated by Django 4.2.5 on 2024-02-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgramingLanguage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programminglanguage',
            name='lang_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
