# Generated by Django 4.2.5 on 2024-03-15 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProgramingLanguage', '0002_programminglanguage_lang_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programminglanguage',
            old_name='lang_id',
            new_name='language_id',
        ),
    ]
