# Generated by Django 4.2.5 on 2024-02-18 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '__first__'),
        ('ProgramingLanguage', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to='Employee.employee')),
                ('programming_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='ProgramingLanguage.programminglanguage')),
            ],
        ),
    ]
