# Generated by Django 4.2.5 on 2024-02-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_alter_course_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ImageURL',
            field=models.ImageField(blank=True, null=True, upload_to='Course/coures-images'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=6),
        ),
    ]
