# Generated by Django 4.2.5 on 2024-02-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_course_imageurl_course_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='ImageURL',
            new_name='imageURL',
        ),
    ]
