# Generated by Django 4.2.5 on 2024-03-17 00:05

import Course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_alter_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='programming_language',
        ),
        migrations.AddField(
            model_name='course',
            name='videoFile',
            field=models.FileField(blank=True, null=True, upload_to=Course.models.video_upload_location),
        ),
        migrations.AlterField(
            model_name='course',
            name='imageURL',
            field=models.ImageField(blank=True, null=True, upload_to='Course/course-images'),
        ),
    ]
