# Generated by Django 4.2.5 on 2024-03-25 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
        ('Course', '0006_remove_course_programming_language_course_videofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Category.category'),
        ),
    ]
