# Generated by Django 4.2.5 on 2024-03-27 00:10

import Course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0007_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='demo',
            field=models.FileField(blank=True, null=True, upload_to=Course.models.video_upload_location),
        ),
    ]
