# Generated by Django 4.2.11 on 2024-04-02 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BindingCourse', '0001_initial'),
        ('Course', '0008_course_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='binding_course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='BindingCourse.bindingcourse'),
        ),
    ]
