# Generated by Django 4.2.11 on 2024-04-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0001_initial'),
        ('Course', '0010_alter_course_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='courses', to='Video.video'),
        ),
    ]
