# Generated by Django 4.2.11 on 2024-04-30 02:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_remove_student_enrolled_courses'),
        ('Course', '0011_course_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='average_rank',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='StudentCourseRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_ranks', to='Course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_ranks', to='Student.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
