# Generated by Django 4.2.11 on 2024-05-13 23:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0012_course_average_rank_studentcourserank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourserank',
            name='rank',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
