# Generated by Django 4.2.5 on 2024-02-18 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProgramingLanguage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=None, upload_to='Summary/summary_files/')),
                ('language', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='ProgramingLanguage.programminglanguage')),
            ],
            options={
                'verbose_name_plural': 'Summaries',
            },
        ),
    ]
