# Generated by Django 4.2.5 on 2024-02-21 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProgramingLanguage', '0001_initial'),
        ('Summary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='language',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='ProgramingLanguage.programminglanguage'),
        ),
    ]
