# Generated by Django 4.2.11 on 2024-05-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0003_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
