# Generated by Django 4.2.11 on 2024-04-02 15:57

import BindingCourse.models
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '0003_remove_employee_position_and_more'),
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BindingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=50.0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('imageURL', models.ImageField(blank=True, null=True, upload_to='Course/course-images')),
                ('videoFile', models.FileField(blank=True, null=True, upload_to=BindingCourse.models.video_upload_location)),
                ('demo', models.FileField(blank=True, null=True, upload_to=BindingCourse.models.video_upload_location)),
                ('approved', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Category.category')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bindingcourses', to='Employee.employee')),
            ],
        ),
    ]
