# Generated by Django 4.2.11 on 2024-04-09 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_alter_employee_programming_languages'),
        ('BindingCourse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bindingcourse',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bindingcourses', to='Employee.employee'),
        ),
    ]
