# Generated by Django 4.2.11 on 2024-04-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0001_initial'),
        ('BindingCourse', '0002_alter_bindingcourse_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bindingcourse',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='bindingcourses', to='Video.video'),
        ),
    ]
