# Generated by Django 4.2.11 on 2024-05-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BindingCourse', '0003_bindingcourse_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='bindingcourse',
            name='is_readed',
            field=models.BooleanField(default=False),
        ),
    ]
