# Generated by Django 4.2.5 on 2024-03-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgramingLanguage', '0003_rename_lang_id_programminglanguage_language_id'),
        ('Employee', '0002_employee_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.AlterField(
            model_name='employee',
            name='programming_languages',
            field=models.ManyToManyField(blank=True, null=True, related_name='employees', to='ProgramingLanguage.programminglanguage'),
        ),
    ]
