# Generated by Django 4.2.11 on 2024-04-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgramingLanguage', '0003_rename_lang_id_programminglanguage_language_id'),
        ('Employee', '0003_remove_employee_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='programming_languages',
            field=models.ManyToManyField(blank=True, related_name='employees', to='ProgramingLanguage.programminglanguage'),
        ),
    ]
