# Generated by Django 4.2.11 on 2024-04-09 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_alter_employee_programming_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='programming_languages',
        ),
    ]
