# Generated by Django 4.2.11 on 2024-05-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BindingMeeting', '0002_alter_bindingmeeting_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bindingmeeting',
            name='message',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
