# Generated by Django 4.2.11 on 2024-05-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BindingMeeting', '0003_alter_bindingmeeting_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='bindingmeeting',
            name='is_readed',
            field=models.BooleanField(default=False),
        ),
    ]
