# Generated by Django 4.2.11 on 2024-04-06 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProgramingLanguage', '0003_rename_lang_id_programminglanguage_language_id'),
        ('BindingBook', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('binding_book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='BindingBook.bindingbook')),
                ('programming_language', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booksprograminglang', to='ProgramingLanguage.programminglanguage')),
            ],
        ),
    ]
