# Generated by Django 4.2.5 on 2024-02-18 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProgramingLanguage', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('programming_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='ProgramingLanguage.programminglanguage')),
            ],
        ),
    ]
