# Generated by Django 4.2.5 on 2024-02-21 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProgramingLanguage', '0001_initial'),
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='programming_language',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='ProgramingLanguage.programminglanguage'),
        ),
    ]
