# Generated by Django 4.2.11 on 2024-04-06 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0009_course_binding_course'),
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='programming_language',
        ),
        migrations.AddField(
            model_name='book',
            name='course',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookscourse', to='Course.course'),
        ),
    ]
