# Generated by Django 4.2.11 on 2024-05-04 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student', '0002_remove_student_enrolled_courses'),
        ('BindingMeeting', '0001_initial'),
        ('Employee', '0005_remove_employee_programming_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('message', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('binding_meeting', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meet', to='BindingMeeting.bindingmeeting')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_meetings', to='Employee.employee')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_meetings', to='Student.student')),
            ],
        ),
    ]
