# Generated by Django 4.2.11 on 2024-05-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='approved',
        ),
    ]
