# Generated by Django 4.2.11 on 2024-05-04 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BindingMeeting', '0003_alter_bindingmeeting_message'),
        ('Meeting', '0002_remove_meeting_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='binding_meeting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meet', to='BindingMeeting.bindingmeeting'),
        ),
    ]
