# Generated by Django 4.2.11 on 2024-05-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0003_alter_meeting_binding_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_readed',
            field=models.BooleanField(default=False),
        ),
    ]
