# Generated by Django 4.2.11 on 2024-05-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0004_meeting_is_readed'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
