# Generated by Django 4.2.11 on 2024-05-07 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BindingMeeting', '0004_bindingmeeting_is_readed'),
        ('Meeting', '0005_meeting_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='binding_meeting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meet', to='BindingMeeting.bindingmeeting'),
        ),
    ]
