# Generated by Django 4.2.11 on 2024-05-07 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BindingMeeting', '0004_bindingmeeting_is_readed'),
        ('Meeting', '0006_alter_meeting_binding_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='binding_meeting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meet', to='BindingMeeting.bindingmeeting'),
        ),
    ]
