# Generated by Django 4.2.11 on 2024-05-07 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0007_alter_meeting_binding_meeting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-date_time']},
        ),
    ]
