# Generated by Django 4.2.11 on 2024-05-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0008_alter_meeting_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['date_time']},
        ),
    ]
