# Generated by Django 4.2.11 on 2024-05-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0009_alter_meeting_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='meeting',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
