# Generated by Django 4.2.5 on 2024-03-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_customuser_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
    ]
