# Generated by Django 4.2.5 on 2024-03-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='User/defualt.jpg/', null=True, upload_to='User/user_images/'),
        ),
    ]
