# Generated by Django 4.2.5 on 2024-03-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, default='male', max_length=10, null=True),
        ),
    ]
