# Generated by Django 4.2.5 on 2024-03-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='defualt.jpg/', null=True, upload_to='user_images/'),
        ),
    ]
