# Generated by Django 4.2.11 on 2024-05-14 11:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Video', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videoview',
            unique_together={('video', 'user')},
        ),
    ]
